version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_USER=johndoe
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
